# https://attacomsian.com/blog/spring-data-jpa-h2-database
# https://www.baeldung.com/spring-boot-h2-database
spring:
  datasource:
    url: jdbc:oracle:thin:@server:port:databasename
    driver-class-name: oracle.jdbc.OracleDriver
    username: sa
    password:
  #    password: password
    hikari:
      maximum-pool-size: 5 #30
      connection-timeout: 20000 #30000
      idle-timeout: 300000 # 600000
      max-lifetime: 1200000 # 1800000
      minimum-idle: 1 #30
  jpa:
    database-platform: "org.hibernate.dialect.Oracle10gDialect"
    show-sql: true
    hibernate:
      ddl-auto: create