# https://attacomsian.com/blog/spring-data-jpa-h2-database
# https://www.baeldung.com/spring-boot-h2-database
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DBNAME:test}?serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false
#    driver-class-name:
    username: mysqlusername
    password: mysqlpassword
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect