springdoc:
  swagger-ui:
    path: /v3/swagger-ui.html
  api-docs:
    enabled: true
    path: /v3/api-docs
  show:
    actuator: true

server:
  port: 8090
  address: localhost


application:
  version: '@project.version@'

springdocproperties:
  apiinfo:
    title: "SPRINGDOC OPENAPI 3 SAMPLE"
    description: "API description oh yeah"
    terms-of-service: "http://swagger.io/terms/"
    version: '@project.version@'
    contact:
      name: "filip"
      url: "http://"
      email: "abc@email.com"
    license:
      name: "Apache 2.0"
      url: "http://springdoc.org"
  servers:
    - url: http://${server.address}:${server.port}
      description: "Generated server url"
      variables:
        - username:
            - default: demo
            - description: this value is assigned by the service provider, in this example `gigantic-server.com`
        - port:
            - enum:
                - '8443'
                - '443'
        - basePath:
            # open meaning there is the opportunity to use special base paths as assigned by the provider, default is `v2`
            - default: v2
    - url: "http://localhost:8089"
      description: "desc 2"


# https://attacomsian.com/blog/spring-data-jpa-h2-database
# https://www.baeldung.com/spring-boot-h2-database
spring:
  datasource:
    url: jdbc:h2:mem:testdb
#    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
#    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

#  spring.datasource.url=jdbc:h2:~/test
#  spring.datasource.driverClassName=org.h2.Driver
#  spring.datasource.username=sa
#  spring.datasource.password=
