# https://attacomsian.com/blog/spring-data-jpa-h2-database
# https://www.baeldung.com/spring-boot-h2-database
spring:
  datasource:
    url: jdbc:mysql://${POSTGRESQL_HOST:localhost}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_DBNAME:test}
#    driver-class-name:
    username: postgres
    password: password
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create