

springdoc:
  swagger-ui:
    path: /v3/swagger-ui.html
  api-docs:
    enabled: true
    path: /v3/api-docs
  show:
    actuator: true

server:
  port: 8090
  address: localhost
  http2:
    enabled: true
  servlet:
    context-path: /
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json


application:
  version: '@project.version@'

springdocproperties:
  apiinfo:
    title: "SPRINGDOC OPENAPI 3 SAMPLE"
#    description: "API description oh yeah"
    description: "This is a sample server Petstore server.  You can find out more about
    Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).
    For this sample, you can use the api key `special-key` to test the authorization filters."
    terms-of-service: "http://swagger.io/terms/"
    version: '@project.version@'
    contact:
      name: "Filip Vanden Eynde"
#      url: "http://"
#      email: "abc@email.com"
    license:
      name: "Apache 2.0"
      url: "http://springdoc.org"
  servers:
    - url: http://${server.address}:${server.port}
      description: "Generated server url"
      variables:
        - username:
            - default: demo
            - description: this value is assigned by the service provider, in this example `gigantic-server.com`
        - port:
            - enum:
                - '8443'
                - '443'
        - basePath:
            # open meaning there is the opportunity to use special base paths as assigned by the provider, default is `v2`
            - default: v2
    - url: "http://localhost:8089"
      description: "desc 2"

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create # drop and create table, good for testing, comment this in production
      use-new-id-generator-mappings: false #`hibernate_sequence' doesn't exist
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false #Turn Statistics on
  resources:
    cache:
      period: 31536000
      cachecontrol:
        max-age: 31536000
    chain:
      html-application-cache: true
      enabled: true
      strategy:
        content:
          enabled: true
          paths: /webjars/swagger-ui/**.*
  main:
    banner-mode: console
  profiles:
    active: h2database
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: Europe/Brussels
